language: node_js
node_js:
  - "12"

install:
  - npm ci

cache:
  directories:
    - "$HOME/.npm"

stages:
  - name: test
    if: type = pull_request AND branch = development
  - name: deploy
    if: type = push AND branch = development

jobs:
  include:
    - stage: test
      script:
        - npx eslint ./src
        - npm run build
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: development
